### ISSUE TITLE
80040154 Class not registered

### ISSUE THREAD

**Issue by hubaolinlei** [PNNL-Comp-Mass-Spec/DeconTools#3]
I could not run the software on win10. Here is error log info. Could you help me with this problem?

8/7/2017 2:36:09 PM	DeconTools.Backend.dll version = v2.0.6397.26575
8/7/2017 2:36:09 PM	UIMFLibrary version = v3.3.0.0
8/7/2017 2:36:09 PM	ERROR message= Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
8/7/2017 2:36:09 PM	ERROR type= System.Runtime.InteropServices.COMException (0x80040154): Retrieving the COM class factory for component with CLSID {1D23188D-53FE-4C25-B032-DC70ACDBDC02} failed due to the following error: 80040154 Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DeconTools.Backend.Runs.XCaliburRun2..ctor()
   at DeconTools.Backend.Runs.XCaliburRun2..ctor(String filename)
   at DeconTools.Backend.Runs.RunFactory.CreateRun(String filename)
   at DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow(String datasetFileName, String parameterFile, String outputFolderPath, BackgroundWorker backgroundWorker, Boolean useNewDeconToolsParameterObjects)
8/7/2017 2:36:09 PM	STACKTRACE = Stack trace: 
  DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow
  DeconTools.Backend.Runs.RunFactory.CreateRun
  DeconTools.Backend.Runs.XCaliburRun2..ctor
  DeconTools.Backend.Runs.XCaliburRun2..ctor
  System.Activator.CreateInstance
  System.Activator.CreateInstance
  System.RuntimeType.CreateInstanceDefaultCtor
  System.RuntimeType.CreateInstanceSlow
  System.RuntimeTypeHandle.CreateInstance

**Comment by alchemistmatt** [comment]
`{1d23188d-53fe-4c25-b032-dc70acdbdc02}` is the COM ID for MSFileReader.  I presume you're trying to process a Thermo .Raw file?  You need to download MSFileReader v3 from Thermo. Steps:
- Create an account at https://thermo.flexnetoperations.com/control/thmo/login 
- Login then click category "Utility Software"
- Download MSFileReader 3.1 SP4
- Run the installer and install both the 32-bit and 64-bit versions.

**Comment by hubaolinlei** [comment]
Thank you so much for fully addressing my question!
