### ISSUE TITLE
Support for Agilent IMS-QTOF files (version 3)?

### ISSUE THREAD

**Issue by wyu** [PNNL-Comp-Mass-Spec/DeconTools#6]
Thanks to the team for the excellent tool for the community, especially for IMS data. We've recently encountered an issue with the files from an IMS-QTOF instrument. It seems to suggest that the *.d is supported only up to version 2. Is there a work around to this problem?

Wen

11/20/2020 06:58:58	DeconTools.Backend.dll version = v2.0.7370.32964
11/20/2020 06:58:58	UIMFLibrary version = v3.7.3.0
11/20/2020 06:58:58	ERROR message= File version of 3 is not supported (this software supports up to version 2).
11/20/2020 06:58:58	ERROR type= System.IO.InvalidDataException: File version of 3 is not supported (this software supports up to version 2).
   at Agilent.MassSpectrometry.DataAnalysis.MSScanHeaderReader.ValidateHeaderInfo()
   at Agilent.MassSpectrometry.DataAnalysis.MSScanHeaderReader.ReadScanHeader(BinaryReader& indexBinReader, BDAMSScanFileInformation& scanFileInfo)
   at Agilent.MassSpectrometry.DataAnalysis.MSScanInfoMgr.ReadScanInfo(Int64 totNumOfScans, BDAMSScanFileInformation& scanFileInfo)
   at Agilent.MassSpectrometry.DataAnalysis.DataFileMgr.ReadMSDeviceRelatedInfo()
   at Agilent.MassSpectrometry.DataAnalysis.DataFileMgr.OpenDataFile(String fileName)
   at Agilent.MassSpectrometry.DataAnalysis.BDADataAccess.Agilent.MassSpectrometry.DataAnalysis.IBDADataAccess.OpenDataFile(String fileName, Boolean bOptimizeFileHandling)
   at DeconTools.Backend.Runs.AgilentDRun..ctor(String dataFileName) in F:\Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Runs\AgilentDRun.cs:line 47
   at DeconTools.Backend.Runs.RunFactory.CreateRun(String filename) in F:\Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Runs\RunFactory.cs:line 92
   at DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow(String datasetFileName, String parameterFile, String outputDirectoryPath, BackgroundWorker backgroundWorker, Boolean useNewDeconToolsParameterObjects) in F:\Documents\Projects\GordonSlysz\DeconTools_IQ\DeconTools.Backend\Workflows\ScanBasedWorkflow.cs:line 85
11/20/2020 06:58:58	STACKTRACE = Stack trace: 
  DeconTools.Backend.Workflows.ScanBasedWorkflow.CreateWorkflow in ScanBasedWorkflow.cs:line 85
  DeconTools.Backend.Runs.RunFactory.CreateRun in RunFactory.cs:line 92
  DeconTools.Backend.Runs.AgilentDRun..ctor:line 47
  Agilent.MassSpectrometry.DataAnalysis.BDADataAccess.Agilent.MassSpectrometry.DataAnalysis.IBDADataAccess.OpenDataFile
  Agilent.MassSpectrometry.DataAnalysis.DataFileMgr.OpenDataFile
  
  Agilent.MassSpectrometry.DataAnalysis.MSScanInfoMgr.ReadScanInfo
  Agilent.MassSpectrometry.DataAnalysis.MSScanHeaderReader.ReadScanHeader
  
   in AgilentDRun.cs

**Comment by alchemistmatt** [comment]
I found a newer version of MassSpecDataReader.dll and have uploaded a new version of DeconConsole.exe that is compiled again it.  Give Release 1.1.7629 a try:
* https://github.com/PNNL-Comp-Mass-Spec/DeconTools/releases/
